WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000112AD536F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000112AD5711D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000112AD571590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session